#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.application.name=Springboot-project01
##spring.datasource.url=jdbc:mysql://localhost:3306/shenren
#spring.datasource.username=root
#spring.datasource.password=123456
## 配置mybatis的日志输�?
#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis.mapper-locations=classpath:itheima/*.xml